-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 22:36:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ygeiopolis_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ygeiopolis_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ygeiopolis_db` DEFAULT CHARACTER SET utf8 ;
USE `Ygeiopolis_db` ;

-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`patient` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`patient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_amka` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `father_name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) UNSIGNED NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `weight` DECIMAL(5,2) NULL,
  `height` DECIMAL(5,2) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `profession` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `blood_type` VARCHAR(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `patient_amka_UNIQUE` ON `Ygeiopolis_db`.`patient` (`patient_amka` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`staff` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`staff` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_amka` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `hire_date` DATE NOT NULL,
  `staff_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `staff_amka_UNIQUE` ON `Ygeiopolis_db`.`staff` (`staff_amka` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `Ygeiopolis_db`.`staff` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`contact_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`contact_person` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`contact_person` (
  `id` VARCHAR(8) NOT NULL,
  `relation` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `patient_id`),
  CONSTRAINT `fk_contact_person_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contact_person_patient_idx` ON `Ygeiopolis_db`.`contact_person` (`patient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`doc_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`doc_grade` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`doc_grade` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`doc_grade` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`doc_spec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`doc_spec` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`doc_spec` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`doc_spec` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`doctor` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`doctor` (
  `id` INT UNSIGNED NOT NULL,
  `license_no` VARCHAR(45) NOT NULL,
  `supervisor_id` INT UNSIGNED NULL,
  `doc_grade_id` INT UNSIGNED NOT NULL,
  `doc_spec_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `doc_id`
    FOREIGN KEY (`id`)
    REFERENCES `Ygeiopolis_db`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supervisor_id`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_grade_id`
    FOREIGN KEY (`doc_grade_id`)
    REFERENCES `Ygeiopolis_db`.`doc_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_spec_id`
    FOREIGN KEY (`doc_spec_id`)
    REFERENCES `Ygeiopolis_db`.`doc_spec` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';

CREATE INDEX `supervisor_id_idx` ON `Ygeiopolis_db`.`doctor` (`supervisor_id` ASC) VISIBLE;

CREATE INDEX `grade_id_idx` ON `Ygeiopolis_db`.`doctor` (`doc_grade_id` ASC) VISIBLE;

CREATE INDEX `spec_id_idx` ON `Ygeiopolis_db`.`doctor` (`doc_spec_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `license_no_UNIQUE` ON `Ygeiopolis_db`.`doctor` (`license_no` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`department` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `beds_no` SMALLINT(5) UNSIGNED NOT NULL,
  `floor` TINYINT(2) NOT NULL,
  `building` VARCHAR(45) NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_department_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_department_doctor1_idx` ON `Ygeiopolis_db`.`department` (`doctor_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`department` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`nurse_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`nurse_grade` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`nurse_grade` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`nurse_grade` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`nurse` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`nurse` (
  `id` INT UNSIGNED NOT NULL,
  `nurse_grade_id` INT UNSIGNED NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `nurse_id`
    FOREIGN KEY (`id`)
    REFERENCES `Ygeiopolis_db`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurse_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurse_grade_id`
    FOREIGN KEY (`nurse_grade_id`)
    REFERENCES `Ygeiopolis_db`.`nurse_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_nurse_department1_idx` ON `Ygeiopolis_db`.`nurse` (`department_id` ASC) VISIBLE;

CREATE INDEX `grade_id_idx` ON `Ygeiopolis_db`.`nurse` (`nurse_grade_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`triage_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`triage_entry` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`triage_entry` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `urg_level` TINYINT(1) UNSIGNED NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  `nurse_id` INT UNSIGNED NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `service_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_triage_entry_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triage_entry_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `Ygeiopolis_db`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triage_entry_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_triage_entry_department1_idx` ON `Ygeiopolis_db`.`triage_entry` (`department_id` ASC) VISIBLE;

CREATE INDEX `fk_triage_entry_nurse1_idx` ON `Ygeiopolis_db`.`triage_entry` (`nurse_id` ASC) VISIBLE;

CREATE INDEX `fk_triage_entry_patient1_idx` ON `Ygeiopolis_db`.`triage_entry` (`patient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`bed` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`bed` (
  `no` INT UNSIGNED NOT NULL,
  `dept_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`no`, `dept_id`),
  CONSTRAINT `fk_bed_dept`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `dept_id_idx` ON `Ygeiopolis_db`.`bed` (`dept_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`hospitalization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`hospitalization` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`hospitalization` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admission_date` DATETIME NOT NULL,
  `discharge_date` DATETIME NULL,
  `total_cost` DECIMAL(10,2) NULL,
  `triage_entry_id` INT UNSIGNED NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `bed_no` INT UNSIGNED NOT NULL,
  `bed_dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_hospitalization_triage_entry1`
    FOREIGN KEY (`triage_entry_id`)
    REFERENCES `Ygeiopolis_db`.`triage_entry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_bed1`
    FOREIGN KEY (`bed_no` , `bed_dept_id`)
    REFERENCES `Ygeiopolis_db`.`bed` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_hospitalization_triage_entry1_idx` ON `Ygeiopolis_db`.`hospitalization` (`triage_entry_id` ASC) VISIBLE;

CREATE INDEX `fk_hospitalization_patient1_idx` ON `Ygeiopolis_db`.`hospitalization` (`patient_id` ASC) VISIBLE;

CREATE INDEX `fk_hospitalization_bed1_idx` ON `Ygeiopolis_db`.`hospitalization` (`bed_no` ASC, `bed_dept_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `triage_entry_id_UNIQUE` ON `Ygeiopolis_db`.`hospitalization` (`triage_entry_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`clinical_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`clinical_room` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`clinical_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`mp_entryB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`mp_entryB` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`mp_entryB` (
  `code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`lab_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`lab_exam` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`lab_exam` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `numeric_result` INT NULL,
  `text_result` TEXT(500) NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `clinical_room_id` INT UNSIGNED NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `mp_entryB_code` VARCHAR(20) NOT NULL,
  `unit` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lab_exam_clinical_room1`
    FOREIGN KEY (`clinical_room_id`)
    REFERENCES `Ygeiopolis_db`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_mp_entryB1`
    FOREIGN KEY (`mp_entryB_code`)
    REFERENCES `Ygeiopolis_db`.`mp_entryB` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lab_exam_clinical_room1_idx` ON `Ygeiopolis_db`.`lab_exam` (`clinical_room_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_hospitalization1_idx` ON `Ygeiopolis_db`.`lab_exam` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_doctor1_idx` ON `Ygeiopolis_db`.`lab_exam` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_mp_entryB1_idx` ON `Ygeiopolis_db`.`lab_exam` (`mp_entryB_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`KEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`KEN` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`KEN` (
  `code` VARCHAR(10) NOT NULL,
  `base_cost` DECIMAL(10,2) NOT NULL,
  `mdh` SMALLINT(5) UNSIGNED NOT NULL,
  `daily_extra_charge` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`insurance_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`insurance_provider` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`insurance_provider` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`insurance_provider` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`medication` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`medication` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `auth_country` VARCHAR(45) NOT NULL,
  `mark_auth_holder` VARCHAR(100) NOT NULL,
  `master_file_loc` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`prescription` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`prescription` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dose` VARCHAR(45) NOT NULL,
  `freq` VARCHAR(45) NOT NULL,
  `pres_day` DATE NOT NULL,
  `exp_date` DATE NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `medication_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prescription_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_medication1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `Ygeiopolis_db`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prescription_patient1_idx` ON `Ygeiopolis_db`.`prescription` (`patient_id` ASC) VISIBLE;

CREATE INDEX `fk_prescription_doctor1_idx` ON `Ygeiopolis_db`.`prescription` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_prescription_medication1_idx` ON `Ygeiopolis_db`.`prescription` (`medication_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `prescription` ON `Ygeiopolis_db`.`prescription` (`medication_id` ASC, `patient_id` ASC, `doctor_id` ASC, `pres_day` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`active_substance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`active_substance` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`active_substance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `Ygeiopolis_db`.`active_substance` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`operating_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`operating_room` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`operating_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`mp_entryA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`mp_entryA` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`mp_entryA` (
  `code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `code_UNIQUE` ON `Ygeiopolis_db`.`mp_entryA` (`code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`surgery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`surgery` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`surgery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `duration` SMALLINT(5) UNSIGNED NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `operating_room_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `mp_entryA_code` VARCHAR(20) NOT NULL,
  `start_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_surgery_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_operating_room1`
    FOREIGN KEY (`operating_room_id`)
    REFERENCES `Ygeiopolis_db`.`operating_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_mp_entryA1`
    FOREIGN KEY (`mp_entryA_code`)
    REFERENCES `Ygeiopolis_db`.`mp_entryA` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_surgery_hospitalization1_idx` ON `Ygeiopolis_db`.`surgery` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_operating_room1_idx` ON `Ygeiopolis_db`.`surgery` (`operating_room_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_doctor1_idx` ON `Ygeiopolis_db`.`surgery` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_mp_entryA1_idx` ON `Ygeiopolis_db`.`surgery` (`mp_entryA_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`evaluation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qual_med_care` TINYINT(1) UNSIGNED NOT NULL,
  `qual_nurse_care` TINYINT(1) UNSIGNED NOT NULL,
  `cleanness` TINYINT(1) UNSIGNED NOT NULL,
  `food` TINYINT(1) UNSIGNED NOT NULL,
  `tot_experience` TINYINT(1) UNSIGNED NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_evaluation_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evaluation_hospitalization1_idx` ON `Ygeiopolis_db`.`evaluation` (`hospitalization_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `hospitalization_id_UNIQUE` ON `Ygeiopolis_db`.`evaluation` (`hospitalization_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`med_proc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`med_proc` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`med_proc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `duration` SMALLINT(5) UNSIGNED NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `clinical_room_id` INT UNSIGNED NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `mp_entryA_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_med_proc_clinical_room1`
    FOREIGN KEY (`clinical_room_id`)
    REFERENCES `Ygeiopolis_db`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_med_proc_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_med_proc_mp_entryA1`
    FOREIGN KEY (`mp_entryA_code`)
    REFERENCES `Ygeiopolis_db`.`mp_entryA` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_examination_clinical_room1_idx` ON `Ygeiopolis_db`.`med_proc` (`clinical_room_id` ASC) VISIBLE;

CREATE INDEX `fk_examination_hospitalization1_idx` ON `Ygeiopolis_db`.`med_proc` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_examination_mp_entryA1_idx` ON `Ygeiopolis_db`.`med_proc` (`mp_entryA_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`hosp_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`hosp_entry` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`hosp_entry` (
  `code` VARCHAR(10) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`admin_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`admin_staff` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`admin_staff` (
  `id` INT UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `office` VARCHAR(45) NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `admin_id`
    FOREIGN KEY (`id`)
    REFERENCES `Ygeiopolis_db`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_staff_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_staff_department1_idx` ON `Ygeiopolis_db`.`admin_staff` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`shift` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`shift` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dept_id` INT UNSIGNED NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `date` DATE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shift_dept`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`triage_symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`triage_symptom` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`triage_symptom` (
  `triage_id` INT UNSIGNED NOT NULL,
  `symptom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`triage_id`, `symptom`),
  CONSTRAINT `fk_triage_symptom_triage`
    FOREIGN KEY (`triage_id`)
    REFERENCES `Ygeiopolis_db`.`triage_entry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`medication_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`medication_tel` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`medication_tel` (
  `med_id` INT UNSIGNED NOT NULL,
  `tel_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`med_id`, `tel_no`),
  CONSTRAINT `fk_med_tel_med`
    FOREIGN KEY (`med_id`)
    REFERENCES `Ygeiopolis_db`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`patient_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`patient_tel` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`patient_tel` (
  `patient_id` INT UNSIGNED NOT NULL,
  `tel_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`patient_id`, `tel_no`),
  CONSTRAINT `fk_patient_tel_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`bed_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`bed_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`bed_img` (
  `bed_no` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `dept_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`bed_no`, `image_url`, `dept_id`),
  CONSTRAINT `fk_bed_img_bed`
    FOREIGN KEY (`bed_no` , `dept_id`)
    REFERENCES `Ygeiopolis_db`.`bed` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `bed_id_idx` ON `Ygeiopolis_db`.`bed_img` (`bed_no` ASC, `dept_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`bed_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`dept_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`dept_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`dept_img` (
  `dept_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`dept_id`, `image_url`),
  CONSTRAINT `fk_dept_img_dept`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`dept_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`op_room_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`op_room_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`op_room_img` (
  `op_room_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`op_room_id`, `image_url`),
  CONSTRAINT `fk_op_room_img_op_room`
    FOREIGN KEY (`op_room_id`)
    REFERENCES `Ygeiopolis_db`.`operating_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`op_room_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`medication_route_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`medication_route_admin` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`medication_route_admin` (
  `med_id` INT UNSIGNED NOT NULL,
  `route_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`med_id`, `route_admin`),
  CONSTRAINT `fk_med_route_med`
    FOREIGN KEY (`med_id`)
    REFERENCES `Ygeiopolis_db`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`contact_person_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`contact_person_tel` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`contact_person_tel` (
  `tel_no` VARCHAR(15) NOT NULL,
  `contact_person_id` VARCHAR(8) NOT NULL,
  `contact_person_patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tel_no`, `contact_person_id`, `contact_person_patient_id`),
  CONSTRAINT `fk_contact_person_tel_contact_person1`
    FOREIGN KEY (`contact_person_id` , `contact_person_patient_id`)
    REFERENCES `Ygeiopolis_db`.`contact_person` (`id` , `patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contact_person_tel_contact_person1_idx` ON `Ygeiopolis_db`.`contact_person_tel` (`contact_person_id` ASC, `contact_person_patient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`patient_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`patient_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`patient_img` (
  `patient_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`patient_id`, `image_url`),
  CONSTRAINT `fk_patient_img_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`patient_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`staff_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`staff_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`staff_img` (
  `staff_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`staff_id`, `image_url`),
  CONSTRAINT `fk_staff_img_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Ygeiopolis_db`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`staff_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`clinical_room_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`clinical_room_img` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`clinical_room_img` (
  `clin_room_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`clin_room_id`, `image_url`),
  CONSTRAINT `fk_clin_room_img_clin_room`
    FOREIGN KEY (`clin_room_id`)
    REFERENCES `Ygeiopolis_db`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `Ygeiopolis_db`.`clinical_room_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`exam_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`exam_doc` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`exam_doc` (
  `med_proc_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`med_proc_id`, `doctor_id`),
  CONSTRAINT `fk_exam_doc_med_proc1`
    FOREIGN KEY (`med_proc_id`)
    REFERENCES `Ygeiopolis_db`.`med_proc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_doc_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_exam_doc_doctor1_idx` ON `Ygeiopolis_db`.`exam_doc` (`doctor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`exam_nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`exam_nurse` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`exam_nurse` (
  `med_proc_id` INT UNSIGNED NOT NULL,
  `nurse_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`med_proc_id`, `nurse_id`),
  CONSTRAINT `fk_exam_nurse_med_proc1`
    FOREIGN KEY (`med_proc_id`)
    REFERENCES `Ygeiopolis_db`.`med_proc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_nurse_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `Ygeiopolis_db`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_exam_nurse_nurse1_idx` ON `Ygeiopolis_db`.`exam_nurse` (`nurse_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`admission_diag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`admission_diag` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`admission_diag` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `hosp_entry_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `hosp_entry_code`),
  CONSTRAINT `fk_admission_diag_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admission_diag_idc101`
    FOREIGN KEY (`hosp_entry_code`)
    REFERENCES `Ygeiopolis_db`.`hosp_entry` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admission_diag_idc101_idx` ON `Ygeiopolis_db`.`admission_diag` (`hosp_entry_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`discharge_diag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`discharge_diag` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`discharge_diag` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `hosp_entry_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `hosp_entry_code`),
  CONSTRAINT `fk_discharge_diag_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discharge_diag_idc101`
    FOREIGN KEY (`hosp_entry_code`)
    REFERENCES `Ygeiopolis_db`.`hosp_entry` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_discharge_diag_idc101_idx` ON `Ygeiopolis_db`.`discharge_diag` (`hosp_entry_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`assigned_ken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`assigned_ken` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`assigned_ken` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `KEN_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `KEN_code`),
  CONSTRAINT `fk_assigned_ken_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `Ygeiopolis_db`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assigned_ken_KEN1`
    FOREIGN KEY (`KEN_code`)
    REFERENCES `Ygeiopolis_db`.`KEN` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_assigned_ken_KEN1_idx` ON `Ygeiopolis_db`.`assigned_ken` (`KEN_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`doc_belongs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`doc_belongs` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`doc_belongs` (
  `department_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`department_id`, `doctor_id`),
  CONSTRAINT `fk_doc_belongs_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `Ygeiopolis_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doc_belongs_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_doc_belongs_doctor1_idx` ON `Ygeiopolis_db`.`doc_belongs` (`doctor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`has_insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`has_insurance` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`has_insurance` (
  `patient_id` INT UNSIGNED NOT NULL,
  `insurance_provider_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patient_id`, `insurance_provider_id`),
  CONSTRAINT `fk_has_insurance_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_insurance_insurance_provider1`
    FOREIGN KEY (`insurance_provider_id`)
    REFERENCES `Ygeiopolis_db`.`insurance_provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_has_insurance_insurance_provider1_idx` ON `Ygeiopolis_db`.`has_insurance` (`insurance_provider_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`is_allergic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`is_allergic` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`is_allergic` (
  `patient_id` INT UNSIGNED NOT NULL,
  `active_substance_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patient_id`, `active_substance_id`),
  CONSTRAINT `fk_is_allergic_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `Ygeiopolis_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_is_allergic_active_substance1`
    FOREIGN KEY (`active_substance_id`)
    REFERENCES `Ygeiopolis_db`.`active_substance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_is_allergic_active_substance1_idx` ON `Ygeiopolis_db`.`is_allergic` (`active_substance_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`contains` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`contains` (
  `active_substance_id` INT UNSIGNED NOT NULL,
  `medication_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`active_substance_id`, `medication_id`),
  CONSTRAINT `fk_contains_active_substance1`
    FOREIGN KEY (`active_substance_id`)
    REFERENCES `Ygeiopolis_db`.`active_substance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contains_medication1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `Ygeiopolis_db`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contains_medication1_idx` ON `Ygeiopolis_db`.`contains` (`medication_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`help`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`help` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`help` (
  `surgery_id` INT UNSIGNED NOT NULL,
  `staff_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`surgery_id`, `staff_id`),
  CONSTRAINT `fk_help_surgery1`
    FOREIGN KEY (`surgery_id`)
    REFERENCES `Ygeiopolis_db`.`surgery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `Ygeiopolis_db`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_help_staff1_idx` ON `Ygeiopolis_db`.`help` (`staff_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`doctor_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`doctor_shift` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`doctor_shift` (
  `doctor_id` INT UNSIGNED NOT NULL,
  `shift_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`doctor_id`, `shift_id`),
  CONSTRAINT `fk_doctor_shift_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `Ygeiopolis_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_shift_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `Ygeiopolis_db`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_doctor_shift_shift1_idx` ON `Ygeiopolis_db`.`doctor_shift` (`shift_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`nurse_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`nurse_shift` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`nurse_shift` (
  `nurse_id` INT UNSIGNED NOT NULL,
  `shift_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nurse_id`, `shift_id`),
  CONSTRAINT `fk_nurse_shift_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `Ygeiopolis_db`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurse_shift_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `Ygeiopolis_db`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_nurse_shift_shift1_idx` ON `Ygeiopolis_db`.`nurse_shift` (`shift_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ygeiopolis_db`.`admin_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ygeiopolis_db`.`admin_shift` ;

CREATE TABLE IF NOT EXISTS `Ygeiopolis_db`.`admin_shift` (
  `admin_staff_id` INT UNSIGNED NOT NULL,
  `shift_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`admin_staff_id`, `shift_id`),
  CONSTRAINT `fk_admin_shift_admin_staff1`
    FOREIGN KEY (`admin_staff_id`)
    REFERENCES `Ygeiopolis_db`.`admin_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_shift_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `Ygeiopolis_db`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_shift_admin_staff1_idx` ON `Ygeiopolis_db`.`admin_shift` (`admin_staff_id` ASC) VISIBLE;

CREATE INDEX `fk_admin_shift_shift1_idx` ON `Ygeiopolis_db`.`admin_shift` (`shift_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
