-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 02:49:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_amka` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `father_name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) UNSIGNED NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `weight` DECIMAL(5,2) NULL,
  `height` DECIMAL(5,2) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `profession` VARCHAR(45) NULL,
  `nationality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `patient_amka_UNIQUE` ON `mydb`.`patient` (`patient_amka` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` INT UNSIGNED NOT NULL,
  `staff_amka` VARCHAR(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` TINYINT(3) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `hire_date` DATE NOT NULL,
  `staff_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `staff_amka_UNIQUE` ON `mydb`.`staff` (`staff_amka` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`staff` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contact_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact_person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact_person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `relation` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doc_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doc_grade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doc_grade` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`doc_grade` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`doc_spec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doc_spec` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doc_spec` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`doc_spec` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `id` INT UNSIGNED NOT NULL,
  `license_no` VARCHAR(45) NOT NULL,
  `supervisor_id` INT UNSIGNED NULL,
  `doc_grade_id` INT UNSIGNED NOT NULL,
  `doc_spec_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `doc_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supervisor_id`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_id`
    FOREIGN KEY (`doc_grade_id`)
    REFERENCES `mydb`.`doc_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `spec_id`
    FOREIGN KEY (`doc_spec_id`)
    REFERENCES `mydb`.`doc_spec` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';

CREATE INDEX `supervisor_id_idx` ON `mydb`.`doctor` (`supervisor_id` ASC) VISIBLE;

CREATE INDEX `grade_id_idx` ON `mydb`.`doctor` (`doc_grade_id` ASC) VISIBLE;

CREATE INDEX `spec_id_idx` ON `mydb`.`doctor` (`doc_spec_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `license_no_UNIQUE` ON `mydb`.`doctor` (`license_no` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `beds_no` SMALLINT(5) UNSIGNED NOT NULL,
  `floor` TINYINT(2) NOT NULL,
  `building` VARCHAR(45) NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_department_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_department_doctor1_idx` ON `mydb`.`department` (`doctor_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`department` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`nurse_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nurse_grade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nurse_grade` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`nurse_grade` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nurse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nurse` (
  `id` INT UNSIGNED NOT NULL,
  `nurse_grade_id` INT UNSIGNED NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `nurse_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurse_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grade_id`
    FOREIGN KEY (`nurse_grade_id`)
    REFERENCES `mydb`.`nurse_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_nurse_department1_idx` ON `mydb`.`nurse` (`department_id` ASC) VISIBLE;

CREATE INDEX `grade_id_idx` ON `mydb`.`nurse` (`nurse_grade_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`triage_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`triage_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`triage_entry` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `urg_level` TINYINT(1) UNSIGNED NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  `nurse_id` INT UNSIGNED NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_triage_entry_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triage_entry_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `mydb`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triage_entry_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_triage_entry_department1_idx` ON `mydb`.`triage_entry` (`department_id` ASC) VISIBLE;

CREATE INDEX `fk_triage_entry_nurse1_idx` ON `mydb`.`triage_entry` (`nurse_id` ASC) VISIBLE;

CREATE INDEX `fk_triage_entry_patient1_idx` ON `mydb`.`triage_entry` (`patient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bed` (
  `no` INT UNSIGNED NOT NULL,
  `dept_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`no`, `dept_id`),
  CONSTRAINT `dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `dept_id_idx` ON `mydb`.`bed` (`dept_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`hospitalization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hospitalization` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hospitalization` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admission_date` DATETIME NOT NULL,
  `discharge_date` DATETIME NULL,
  `total_cost` DECIMAL(10,2) NULL,
  `triage_entry_id` INT UNSIGNED NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `bed_no` INT UNSIGNED NOT NULL,
  `bed_dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_hospitalization_triage_entry1`
    FOREIGN KEY (`triage_entry_id`)
    REFERENCES `mydb`.`triage_entry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_bed1`
    FOREIGN KEY (`bed_no` , `bed_dept_id`)
    REFERENCES `mydb`.`bed` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_hospitalization_triage_entry1_idx` ON `mydb`.`hospitalization` (`triage_entry_id` ASC) VISIBLE;

CREATE INDEX `fk_hospitalization_patient1_idx` ON `mydb`.`hospitalization` (`patient_id` ASC) VISIBLE;

CREATE INDEX `fk_hospitalization_bed1_idx` ON `mydb`.`hospitalization` (`bed_no` ASC, `bed_dept_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `triage_entry_id_UNIQUE` ON `mydb`.`hospitalization` (`triage_entry_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`clinical_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clinical_room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clinical_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mp_entryB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mp_entryB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mp_entryB` (
  `code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lab_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lab_exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lab_exam` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `result` TEXT(500) NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `clinical_room_id` INT UNSIGNED NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `mp_entryB_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lab_exam_clinical_room1`
    FOREIGN KEY (`clinical_room_id`)
    REFERENCES `mydb`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_exam_mp_entryB1`
    FOREIGN KEY (`mp_entryB_code`)
    REFERENCES `mydb`.`mp_entryB` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lab_exam_clinical_room1_idx` ON `mydb`.`lab_exam` (`clinical_room_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_hospitalization1_idx` ON `mydb`.`lab_exam` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_doctor1_idx` ON `mydb`.`lab_exam` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_lab_exam_mp_entryB1_idx` ON `mydb`.`lab_exam` (`mp_entryB_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`KEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`KEN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`KEN` (
  `code` VARCHAR(10) NOT NULL,
  `base_cost` DECIMAL(10,2) NOT NULL,
  `mdh` SMALLINT(5) UNSIGNED NOT NULL,
  `daily_extra_charge` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insurance_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insurance_provider` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insurance_provider` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`insurance_provider` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medication` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auth_country` VARCHAR(45) NOT NULL,
  `mark_auth_holder` VARCHAR(100) NOT NULL,
  `master_file_loc` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prescription` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dose` VARCHAR(45) NOT NULL,
  `freq` VARCHAR(45) NOT NULL,
  `pres_day` DATE NOT NULL,
  `exp_date` DATE NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `medication_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prescription_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_medication1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `mydb`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prescription_patient1_idx` ON `mydb`.`prescription` (`patient_id` ASC) VISIBLE;

CREATE INDEX `fk_prescription_doctor1_idx` ON `mydb`.`prescription` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_prescription_medication1_idx` ON `mydb`.`prescription` (`medication_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `prescription` ON `mydb`.`prescription` (`medication_id` ASC, `patient_id` ASC, `doctor_id` ASC, `pres_day` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`active_substance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`active_substance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`active_substance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`active_substance` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`operating_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`operating_room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`operating_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mp_entryA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mp_entryA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mp_entryA` (
  `code` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `code_UNIQUE` ON `mydb`.`mp_entryA` (`code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`surgery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`surgery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`surgery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `duration` SMALLINT(5) UNSIGNED NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `operating_room_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  `mp_entryA_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_surgery_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_operating_room1`
    FOREIGN KEY (`operating_room_id`)
    REFERENCES `mydb`.`operating_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surgery_mp_entryA1`
    FOREIGN KEY (`mp_entryA_code`)
    REFERENCES `mydb`.`mp_entryA` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_surgery_hospitalization1_idx` ON `mydb`.`surgery` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_operating_room1_idx` ON `mydb`.`surgery` (`operating_room_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_doctor1_idx` ON `mydb`.`surgery` (`doctor_id` ASC) VISIBLE;

CREATE INDEX `fk_surgery_mp_entryA1_idx` ON `mydb`.`surgery` (`mp_entryA_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`evaluation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qual_med_care` TINYINT(1) UNSIGNED NOT NULL,
  `qual_nurse_care` TINYINT(1) UNSIGNED NOT NULL,
  `cleanness` TINYINT(1) UNSIGNED NOT NULL,
  `food` TINYINT(1) UNSIGNED NOT NULL,
  `tot_experience` TINYINT(1) UNSIGNED NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_evaluation_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evaluation_hospitalization1_idx` ON `mydb`.`evaluation` (`hospitalization_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `hospitalization_id_UNIQUE` ON `mydb`.`evaluation` (`hospitalization_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`examination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`examination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`examination` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `duration` SMALLINT(5) UNSIGNED NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `clinical_room_id` INT NOT NULL,
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `mp_entryA_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_examination_clinical_room1`
    FOREIGN KEY (`clinical_room_id`)
    REFERENCES `mydb`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examination_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examination_mp_entryA1`
    FOREIGN KEY (`mp_entryA_code`)
    REFERENCES `mydb`.`mp_entryA` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_examination_clinical_room1_idx` ON `mydb`.`examination` (`clinical_room_id` ASC) VISIBLE;

CREATE INDEX `fk_examination_hospitalization1_idx` ON `mydb`.`examination` (`hospitalization_id` ASC) VISIBLE;

CREATE INDEX `fk_examination_mp_entryA1_idx` ON `mydb`.`examination` (`mp_entryA_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`hosp_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hosp_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hosp_entry` (
  `code` VARCHAR(10) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_staff` (
  `id` INT UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `office` VARCHAR(45) NOT NULL,
  `department_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `admin_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_staff_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_staff_department1_idx` ON `mydb`.`admin_staff` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`shift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`shift` (
  `no` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dept_id` INT UNSIGNED NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `date` DATE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`no`, `dept_id`),
  CONSTRAINT `dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`triage_symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`triage_symptom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`triage_symptom` (
  `triage_id` INT UNSIGNED NOT NULL,
  `symptom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`triage_id`, `symptom`),
  CONSTRAINT `triage_id`
    FOREIGN KEY (`triage_id`)
    REFERENCES `mydb`.`triage_entry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medication_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medication_tel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medication_tel` (
  `med_id` INT UNSIGNED NOT NULL,
  `tel_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`med_id`, `tel_no`),
  CONSTRAINT `med_id`
    FOREIGN KEY (`med_id`)
    REFERENCES `mydb`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_tel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_tel` (
  `patient_id` INT UNSIGNED NOT NULL,
  `tel_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`patient_id`, `tel_no`),
  CONSTRAINT `patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bed_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bed_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bed_img` (
  `bed_no` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bed_no`, `image_url`, `dept_id`),
  CONSTRAINT `bed_id`
    FOREIGN KEY (`bed_no` , `dept_id`)
    REFERENCES `mydb`.`bed` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `bed_id_idx` ON `mydb`.`bed_img` (`bed_no` ASC, `dept_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`bed_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`dept_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dept_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dept_img` (
  `dept_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`dept_id`, `image_url`),
  CONSTRAINT `dept_id`
    FOREIGN KEY (`dept_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`dept_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`op_room_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`op_room_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`op_room_img` (
  `op_room_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`op_room_id`, `image_url`),
  CONSTRAINT `op_room_id`
    FOREIGN KEY (`op_room_id`)
    REFERENCES `mydb`.`operating_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`op_room_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`medication_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medication_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medication_img` (
  `med_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`med_id`, `image_url`),
  CONSTRAINT `med_id`
    FOREIGN KEY (`med_id`)
    REFERENCES `mydb`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`medication_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`medication_route_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medication_route_admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medication_route_admin` (
  `med_id` INT UNSIGNED NOT NULL,
  `route_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`med_id`, `route_admin`),
  CONSTRAINT `med_id`
    FOREIGN KEY (`med_id`)
    REFERENCES `mydb`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact_person_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact_person_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact_person_img` (
  `cont_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cont_id`, `image_url`),
  CONSTRAINT `cont_id`
    FOREIGN KEY (`cont_id`)
    REFERENCES `mydb`.`contact_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`contact_person_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contact_person_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact_person_tel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact_person_tel` (
  `cont_id` INT UNSIGNED NOT NULL,
  `tel_no` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cont_id`, `tel_no`),
  CONSTRAINT `cont_id`
    FOREIGN KEY (`cont_id`)
    REFERENCES `mydb`.`contact_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_img` (
  `patient_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`patient_id`, `image_url`),
  CONSTRAINT `patient_id`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`patient_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`staff_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`staff_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`staff_img` (
  `staff_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`staff_id`, `image_url`),
  CONSTRAINT `staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`staff_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`clinical_room_img`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clinical_room_img` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clinical_room_img` (
  `clin_room_id` INT UNSIGNED NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`clin_room_id`, `image_url`),
  CONSTRAINT `clin_room_id`
    FOREIGN KEY (`clin_room_id`)
    REFERENCES `mydb`.`clinical_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_url_UNIQUE` ON `mydb`.`clinical_room_img` (`image_url` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`exam_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exam_doc` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exam_doc` (
  `examination_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`examination_id`, `doctor_id`),
  CONSTRAINT `fk_exam_doc_examination1`
    FOREIGN KEY (`examination_id`)
    REFERENCES `mydb`.`examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_doc_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_exam_doc_doctor1_idx` ON `mydb`.`exam_doc` (`doctor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`exam_nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exam_nurse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exam_nurse` (
  `examination_id` INT UNSIGNED NOT NULL,
  `nurse_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`examination_id`, `nurse_id`),
  CONSTRAINT `fk_exam_nurse_examination1`
    FOREIGN KEY (`examination_id`)
    REFERENCES `mydb`.`examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_nurse_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `mydb`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_exam_nurse_nurse1_idx` ON `mydb`.`exam_nurse` (`nurse_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`admission_diag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admission_diag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admission_diag` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `hosp_entry_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `hosp_entry_code`),
  CONSTRAINT `fk_admission_diag_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admission_diag_idc101`
    FOREIGN KEY (`hosp_entry_code`)
    REFERENCES `mydb`.`hosp_entry` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admission_diag_idc101_idx` ON `mydb`.`admission_diag` (`hosp_entry_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`discharge_diag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`discharge_diag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`discharge_diag` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `hosp_entry_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `hosp_entry_code`),
  CONSTRAINT `fk_discharge_diag_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discharge_diag_idc101`
    FOREIGN KEY (`hosp_entry_code`)
    REFERENCES `mydb`.`hosp_entry` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_discharge_diag_idc101_idx` ON `mydb`.`discharge_diag` (`hosp_entry_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`assigned_ken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`assigned_ken` ;

CREATE TABLE IF NOT EXISTS `mydb`.`assigned_ken` (
  `hospitalization_id` INT UNSIGNED NOT NULL,
  `KEN_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`hospitalization_id`, `KEN_code`),
  CONSTRAINT `fk_assigned_ken_hospitalization1`
    FOREIGN KEY (`hospitalization_id`)
    REFERENCES `mydb`.`hospitalization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assigned_ken_KEN1`
    FOREIGN KEY (`KEN_code`)
    REFERENCES `mydb`.`KEN` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_assigned_ken_KEN1_idx` ON `mydb`.`assigned_ken` (`KEN_code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`doc_belongs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doc_belongs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doc_belongs` (
  `department_id` INT UNSIGNED NOT NULL,
  `doctor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`department_id`, `doctor_id`),
  CONSTRAINT `fk_doc_belongs_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doc_belongs_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_doc_belongs_doctor1_idx` ON `mydb`.`doc_belongs` (`doctor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`has_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`has_contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`has_contact` (
  `contact_person_id` INT UNSIGNED NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`contact_person_id`, `patient_id`),
  CONSTRAINT `fk_has_contact_contact_person1`
    FOREIGN KEY (`contact_person_id`)
    REFERENCES `mydb`.`contact_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_contact_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_has_contact_patient1_idx` ON `mydb`.`has_contact` (`patient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`has_insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`has_insurance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`has_insurance` (
  `patient_id` INT UNSIGNED NOT NULL,
  `insurance_provider_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patient_id`, `insurance_provider_id`),
  CONSTRAINT `fk_has_insurance_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_has_insurance_insurance_provider1`
    FOREIGN KEY (`insurance_provider_id`)
    REFERENCES `mydb`.`insurance_provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_has_insurance_insurance_provider1_idx` ON `mydb`.`has_insurance` (`insurance_provider_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`is_allergic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`is_allergic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`is_allergic` (
  `patient_id` INT UNSIGNED NOT NULL,
  `active_substance_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`patient_id`, `active_substance_id`),
  CONSTRAINT `fk_is_allergic_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_is_allergic_active_substance1`
    FOREIGN KEY (`active_substance_id`)
    REFERENCES `mydb`.`active_substance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_is_allergic_active_substance1_idx` ON `mydb`.`is_allergic` (`active_substance_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contains` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contains` (
  `active_substance_id` INT UNSIGNED NOT NULL,
  `medication_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`active_substance_id`, `medication_id`),
  CONSTRAINT `fk_contains_active_substance1`
    FOREIGN KEY (`active_substance_id`)
    REFERENCES `mydb`.`active_substance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contains_medication1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `mydb`.`medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contains_medication1_idx` ON `mydb`.`contains` (`medication_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`help`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`help` ;

CREATE TABLE IF NOT EXISTS `mydb`.`help` (
  `surgery_id` INT UNSIGNED NOT NULL,
  `staff_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`surgery_id`, `staff_id`),
  CONSTRAINT `fk_help_surgery1`
    FOREIGN KEY (`surgery_id`)
    REFERENCES `mydb`.`surgery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_help_staff1_idx` ON `mydb`.`help` (`staff_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctor_shift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctor_shift` (
  `doctor_id` INT UNSIGNED NOT NULL,
  `shift_no` INT UNSIGNED NOT NULL,
  `shift_dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`doctor_id`, `shift_no`, `shift_dept_id`),
  CONSTRAINT `fk_doctor_shift_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_shift_shift1`
    FOREIGN KEY (`shift_no` , `shift_dept_id`)
    REFERENCES `mydb`.`shift` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_doctor_shift_shift1_idx` ON `mydb`.`doctor_shift` (`shift_no` ASC, `shift_dept_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`nurse_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nurse_shift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nurse_shift` (
  `nurse_id` INT UNSIGNED NOT NULL,
  `shift_no` INT UNSIGNED NOT NULL,
  `shift_dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nurse_id`, `shift_no`, `shift_dept_id`),
  CONSTRAINT `fk_nurse_shift_nurse1`
    FOREIGN KEY (`nurse_id`)
    REFERENCES `mydb`.`nurse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nurse_shift_shift1`
    FOREIGN KEY (`shift_no` , `shift_dept_id`)
    REFERENCES `mydb`.`shift` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_nurse_shift_shift1_idx` ON `mydb`.`nurse_shift` (`shift_no` ASC, `shift_dept_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`admin_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin_shift` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin_shift` (
  `admin_staff_id` INT UNSIGNED NOT NULL,
  `shift_no` INT UNSIGNED NOT NULL,
  `shift_dept_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`admin_staff_id`, `shift_no`, `shift_dept_id`),
  CONSTRAINT `fk_admin_shift_admin_staff1`
    FOREIGN KEY (`admin_staff_id`)
    REFERENCES `mydb`.`admin_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_shift_shift1`
    FOREIGN KEY (`shift_no` , `shift_dept_id`)
    REFERENCES `mydb`.`shift` (`no` , `dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_shift_admin_staff1_idx` ON `mydb`.`admin_shift` (`admin_staff_id` ASC) VISIBLE;

CREATE INDEX `fk_admin_shift_shift1_idx` ON `mydb`.`admin_shift` (`shift_no` ASC, `shift_dept_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
